### 1. Add a New Post
POST http://localhost:5555/post
Content-Type: application/json

{
    "title": "My First Post",
    "content": "This is the content of my first post via REST API",
    "sender": "Donald"
}

### 2. Get All Posts
GET http://localhost:5555/post

### 3. Get Post by ID
GET http://localhost:5555/post/693b302b20cfef4215455a3f

### 4. Get Posts by Sender
GET http://localhost:5555/post?sender=Donald

### 5. Update a Post
PUT http://localhost:5555/post/693b302b20cfef4215455a3f
Content-Type: application/json

{
    "title": "Updated Title",
    "content": "This content has been updated!"
}