@baseUrl = http://localhost:5552

###
### Register a new user
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "auto_test_1@example.com",
    "password": "Password123!",
    "imgUrl": "http://example.com/image.png"
}

### 2. Login User
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "auto_test_1@example.com",
    "password": "Password123!"
}

###

### Get User Profile

GET {{baseUrl}}/users/{{login.response.body._id}}
Authorization: Bearer {{login.response.body.accessToken}}

###

### Update User Profile

PUT {{baseUrl}}/users/{{login.response.body._id}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "imgUrl": "http://example.com/new-image.png"
}

### 

### Create a New Post

# @name createPost
POST {{baseUrl}}/post
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "title": "My TypeScript Post",
    "content": "This is a post created via REST Client with JWT Auth"
}
###

### Get All Posts
GET {{baseUrl}}/post

###

### Get Post by ID

GET {{baseUrl}}/post/{{createPost.response.body._id}}

###

### Update Post

PUT {{baseUrl}}/post/{{createPost.response.body._id}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "title": "Updated Title via REST",
    "content": "Updated content via REST"
}

###

### Delete Post

DELETE {{baseUrl}}/post/{{createPost.response.body._id}}
Authorization: Bearer {{login.response.body.accessToken}}